[project]
name = "caching-proxy"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi==0.128.5",
    "httpx==0.28.1",
    "redis==7.1.0",
    "uvicorn==0.40.0",
]
